### ISSUE TITLE
Adicionar o Controller e o Routes ao projeto

### ISSUE THREAD

**Issue by Guilherme-Joviniano** [cristianocorrea3/pw3-frontend-barueri#1]
Boa tarde!, Gostaria de adicionar o controller e o routes ao projeto para melhorar a arquitetura (MVC) do mesmo

**Comment by cristianocorrea3** [comment]
Olá Guilherme! Tudo bem?
O projeto desse repositório é usado para minhas aulas na Etec de Barueir em um curso de back-end, estou fazendo apenas para demonstrar aos alunos que me pediram um exemplo de acesso via front-end web. Fique a vontade para clonar o repositório.
